name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g pnpm
      - run: pnpm install

      - name: Build Astro app
        run: pnpm run build

      - name: Deploy to GitHub Pages
        run: |
          mkdir gh-pages
          cp -r dist/* gh-pages
          cd gh-pages
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy Astro app to GitHub Pages"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}" master:gh-pages
